### ISSUE TITLE
html - suppress links to current page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#101]
The header bar includes links to 7 pages:

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/f22c28fa-7ad6-4083-81ff-43e850ebdb8e)

When we are on one of those pages, that link should be made a little more dull.  It would even be good to disable that link, if we can from CSS.

I've made progress in this:
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/dc4bf3bd-0614-4ac9-b386-538e09e0f33a)

But, I need @frank-zimmermann to neatly include this JS snippet as a `<SCRIPT> block in the header for the page templates, please:
https://stackoverflow.com/a/51557550/92441

Partially implemented here: https://github.com/DeepBlueCLtd/LegacyMan/pull/540

Note: I've only added the script to the `wh_topic` page template.  IMHO we should move the script to a file on it's own, (`current-handler.js`) and pull this into the page templates.

**Comment by frank-zimmermann** [comment]
For my understanding: If you are on a page, it shouldn't be able to click on the current link, so disable it? Currently, you can click also on the current pages link, right?

**Comment by IanMayo** [comment]
> For my understanding: If you are on a page, it shouldn't be able to click on the current link, so disable it? Currently, you can click also on the current pages link, right?

Thanks for reminding me.  Clicking disabled in this commit: https://github.com/DeepBlueCLtd/LegacyMan/commit/e1e3352ab51a891aad5bc645374d2fe8a62c3027

**Comment by IanMayo** [comment]
Done.
