### ISSUE TITLE
html - page too tall

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#103]
Even though the browser window is tall enough to show the full page (including the footer), the footer bar is never fully visible:
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/f3369b40-b77b-4b6d-b9e9-6a945c3d386f)

**Comment by IanMayo** [comment]
Here is a snapshot of published content: 
[oxygen.zip](https://github.com/DeepBlueCLtd/Fi3ldMan/files/14036043/oxygen.zip)

We require modifications to the `oxygen-webhelp\template\f13ldman.css` file to fix the above layout issue.

**Comment by lebaphi** [comment]
Hi @IanMayo , I think remove line 47 will fix this issue
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/26705621/3f710765-ae42-4c8d-a097-6cff9214b700)

result:
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/26705621/5fe80c0e-422a-4403-8c16-867376081c1e)

**Comment by IanMayo** [comment]
Yes, that looks perfect!

**Comment by IanMayo** [comment]
Fixed in https://github.com/DeepBlueCLtd/LegacyMan/commit/8188354f596ccbc66837318a5b0eed93bca3bb42
