### ISSUE TITLE
Procedure to insert linebreak

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#109]
Document authors frequently use line-breaks to format content.

An example of this is in table headers, where the authors wish the line break to occur in a specific place.

The DITA solution to this is the `<?linebreak?>` processing instruction.  The DITA-OT html transform converts this PI into `<br/>`.

I'm used to doing this in `Text` mode in OxygenXML, but we need an easy way to do this in `Author` mode. I then need to document it in the FieldMan user guide.

It would be _useful_ if we could `register` this snippet in OxygenXML, for easy insertion.  One day we may choose to wrap that as a plugin, but for now the manual steps to do it would be fine.

**Comment by frank-zimmermann** [comment]
I was not able to push a branch, but I can describe it here.

You can navigate to the Preferences > Code Templates and create a new code template, like in the following screenshot:
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/5085576f-12a0-4ea1-b443-12b538ea2e73)

In my case, I also added a shortcut (Shift+Return).

After applying this (we can save this as a Project Option), the editor can now insert the <?linebreak?> PI by pressing Shift_Return, or, by pressing Ctrl+Space:
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/821c0c7d-e614-40bf-a9d8-dbcf417cb4d5)

When start typing "line...", the code snippet is also shown.

I think by documenting to use the shortcut helps a lot.

**Comment by IanMayo** [comment]
This is great, thanks.
