### ISSUE TITLE
Refactoring `class` structure

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#23]
I've had a play with the sample datafile.

I'd like to suggest these improvements, based on usability in OxygenXML please

* [ ] rename `refBody` to `body`
* [ ] rename `classProperties` to `summary` - keep it as first (compulsory) child of `body`
* [ ] move `signature`, `propulsion`, `remarks` to children of `refBody`, following  `summary`.  Items are optional, but in this specified order.
* [ ] remove XML comments, since they are visible in Oxygen (see below)

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/d4d19fc0-a530-4dfb-8b70-a2fc1c5077b2)

**Comment by brahnavank** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class SYSTEM "../../../dtd/class.dtd">
<class id="unit_a">
 <title>Unit_a</title>
 <body>
  
  <summary>
    
    <property>
      
      <proptype></proptype>
      
      <propvalue></propvalue>
    </property>
    <property>
     
     <proptype></proptype>
     
     <propvalue></propvalue>
    </property>
    <property>
     
     <proptype></proptype>
     
     <propvalue></propvalue>
    </property>
    <property>
     
     <proptype></proptype>
     
     <propvalue></propvalue>
    </property>
    <property>
     
     <proptype></proptype>
     
     <propvalue></propvalue>
    </property>
    <property>
     
     <proptype></proptype>
     
     <propvalue></propvalue>
    </property>
  </summary>
  
  
  
  <signatures>
   
   <table><tgroup cols="1"><tbody><row><entry>dummy</entry></row></tbody></tgroup></table>
  </signatures>
  
  
  
  <propulsion>
   
   <p> some narrative content, including a table of varying structure. Plus diagrams, links, etc</p>
  </propulsion>
  
  
  
  
  <remarks>
   
   <span>
  
   </span>
  </remarks> 
 </body>
</class>
