### ISSUE TITLE
Consider XML Author customisations

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#3]
Consider XML Author extension capabilities, and how they can improve user-experience for document author.

Potentially include:
- adding new high level topics, or different types
- finding related content
- drastically reducing the command available in the UI
-

**Comment by frank-zimmermann** [comment]
Oxygen Editor provides the possibility to adapt the Menu and save the changes into a layout file. We can then provide this file to a client. We can decide, what are the needed buttons and menus to reduce the amount of possible functionality.
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/1be213dd-d8bc-4a42-b372-140cfb0ed39c)

**Comment by IanMayo** [comment]
Great. Are you able to test/confirm that these get stored when we `Export Layout`?

**Comment by IanMayo** [comment]
Ok.  Page layout and menu organisation stored in `Layout`, which can be exported & imported.
