### ISSUE TITLE
Include OxygenXML project & template in repo.

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#38]
I have to make a `properties` change for the transformation to work on my PC.

I also expect we will make modifications to the template to suit our export.  So, we should include a template in a `templates` sub-folder of `DITA`, with a readme.txt that explains how to add that template folder to oxygenXML:

https://www.oxygenxml.com/doc/versions/25.1/ug-editor/topics/whr-pt-feature-gallery.html#whr-pt-feature-gallery__custom_templates

**Comment by brahnavank** [comment]
> I have to make a `properties` change for the transformation to work on my PC.
> 
> I also expect we will make modifications to the template to suit our export. So, we should include a template in a `templates` sub-folder of `DITA`, with a readme.txt that explains how to add that template folder to oxygenXML:
> 
> https://www.oxygenxml.com/doc/versions/25.1/ug-editor/topics/whr-pt-feature-gallery.html#whr-pt-feature-gallery__custom_templates

<img width="748" alt="image" src="https://github.com/DeepBlueCLtd/Fi3ldMan/assets/18187509/997d41de-b3ec-473f-8184-c4b71c6ca1f2">

Could you please tell is it this one?

**Comment by IanMayo** [comment]
Yes.
