### ISSUE TITLE
Allow users to navigate current page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#42]
Each `class` is made up from several standard elements (images, summary, signatures, propulsion, remarks).

Users will want to jump between these sections.   We should either provide:
* an extra level of links in the existing left-hand table of contents
* a floating `navigate this page` panel within the class itself.  Permanently floating at top?

**Comment by brahnavank** [comment]
<img width="1436" alt="image" src="https://github.com/DeepBlueCLtd/Fi3ldMan/assets/18187509/2b8d902b-a886-4288-98e1-84f20d27ca42">

Could you please tell Is it the way expected ?

**Comment by IanMayo** [comment]
Yes, the floating menu at the top-right would be acceptable.

Note: as previously discussed, I'm trying to defer the incorporation of DITA-OT into our repo.  So, let's not start this if it introduces that requirement.
