### ISSUE TITLE
Alternate linking strategy

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#50]
In the heatmap we provide target URLs.  These are published files that aren't present during development, which throws an error:

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/40fe3910-bb4b-4393-aecf-2117f2d3f2de)

Is it possible to supply the target URL by referring to the DITA object?

**Comment by brahnavank** [comment]
Output under [#32](https://github.com/DeepBlueCLtd/Fi3ldMan/pull/53) resolve this issue
Please check the output

**Comment by IanMayo** [comment]
Fixed in #32
