### ISSUE TITLE
Supporting data on another page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#57]
Note: for at least one class, we know lots and lots about the propulsion for a platform. So, it's in document of its own. In another case, a group of classes all share the same general propulsion details.   So these link to a shared propulsion document.  I wish to reproduce this in our mock data, so we know what to push the legacy content to.

Ian to generate DITA page containing some sections of data, with IDs.

A mock class should refer to this page, instead of it's own `Propulsion` section.  We need this to work in a way that the author can maintain the content.

I _Guess_ the `propulsion` could either be a `propulsion` element or a `propulsionRef` element that is an XREF to either another document, or a named section in another document.  Aah, the `propulsionRef` should take an optional `title` field. This is what is shown in the in-page navigation block.

The publish process will create an html page for the `class`, and the in-page nav will show the `title` (if present), and link to the target content.

**Comment by IanMayo** [comment]
Hello @brahnavank - does the above strategy seem achievable?

**Comment by brahnavank** [comment]
<img width="498" alt="image" src="https://github.com/DeepBlueCLtd/Fi3ldMan/assets/18187509/6cf69c47-6aa0-4dea-89ae-81b6c820b170">

Something like this?

**Comment by IanMayo** [comment]
Ok.  The PR linked above contains an XML structure that meets this requirement.

I'll modify the branch to include suitable content.
