### ISSUE TITLE
Feature - security warning on headers and footers

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#88]
For every page, we require a security warning in the header and footer.

This will be a full-width div.  The background color will be light green, and contain black 14px arial text saying "COMMERCIALLY SENSITIVE"

Note: this _appears_ to be an article covering how to do this: https://www.dita-ot.org/dev/topics/html-customization-header

**Comment by frank-zimmermann** [comment]
@IanMayo, I created a small screenshot. Please let me know if I understood it right. I would implement it configurable as described in https://github.com/DeepBlueCLtd/Fi3ldMan/issues/89

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/45fb1eb0-37ef-4851-ab89-9bd0e7c68ee6)

**Comment by IanMayo** [comment]
Yes,    @frank-zimmermann  - that looks fine.

**Comment by frank-zimmermann** [comment]
Need to be changed the footer text? 
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/495d2b4b-9a01-4793-b1c3-bf2c7ce3e7f7)

Now I have the possibility to overwrite existing XSLT templates by creating our own XSLT files in the template folder.

**Comment by frank-zimmermann** [comment]
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/f76784e6-6ebe-4592-87d1-878dec9f68e4)

For our own styles, I would create a new CSS file. Changes could of course done in oxygen.css, but for modularity, I would create a new one. Agree?

**Comment by IanMayo** [comment]
> Should the footer text be changed?

That is a [future issue](https://github.com/DeepBlueCLtd/Fi3ldMan/issues/91) to be worked upon

> Now I have the possibility to overwrite existing XSLT templates by creating our own XSLT files in the template folde

This is my favoured sequence for modifying output:
- existing DITA-OT params
- existing Oxgen WebHelp params
- modifying templates in Oxygen publishing template
- using XSL transforms.

For now, I'm happy for them to go at the top of the `oxygen.css` file, please.   Let's  introduce separate  CSS file as a future task - once we know it is justified.
