### ISSUE TITLE
Add Oxygen DITA-OT framework to repo

### ISSUE THREAD

**Issue by frank-zimmermann** [DeepBlueCLtd/Fi3ldMan#94]
Oxygen uses the Built-in DITA publishing engine. It's a folder located in the frameworks directory of the installed Oxygen instance.
Regarding changes in the transformation, the DITA-OT folder should be copied into the repository. The folder to the new location needs to be changed in the file LegacyMan_DITA.xpr.

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/8c060bba-abef-460c-89a6-b4657bcdd4ed)

This is necessary to handle changes in the transformation as dynamic as possible, adapting/reformatting the transformation templates (xsl) as needed.

An example is adding header and footer information, see https://github.com/DeepBlueCLtd/Fi3ldMan/issues/88

**Comment by IanMayo** [comment]
Sure, please create a PR for it.

**Comment by frank-zimmermann** [comment]
@IanMayo, a new branch was created. The DITA-OT folder also contains a folder lib (necessary for transformation)
How do you handle adding .jar files? 
Adding this folder locally or modifying the .gitignore file? lib is currently ignored globally.

**Comment by IanMayo** [comment]
I'm happy to include it, if it's part of the original DITA-OT distribution.

Are all `lib` folders ignored, or just at the top level?

**Comment by frank-zimmermann** [comment]
No, lib/ means all folders.
I would add !DITA-OT/lib/ to not ignore exactly this folder. (Works for me, noew I can add it)

**Comment by IanMayo** [comment]
Yes - that sounds fine Frank.

**Comment by IanMayo** [comment]
We'll close this issue for now, since we're going to try resolving it by just modifying the Oxygen transformation scenario.
