### ISSUE TITLE
Move search bar into header

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#95]
The full-text-search is an amazing capability that my users are really looking forward to.

But, it is expensive in its use of screen-estate:

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/9b5e0b2d-e77c-4a9e-bded-8fc626111abf)

I'd like us to move it into the header bar, please.  So, the header will contain an input-box and search button, and positioned between "Field Manual V4 Feb 2022" and "WELCOME"

When the width of the screen is reduced, the search box should always remain visible - even after the right-hand links have disappeared. (if possible).

This task should be completed by amending the templates in the `template\F13ldMan` folder in the LegacyMan repository.

The outcome of the task will be a Pull Request containing the new publishing template, plus one or more screenshots of the new layout.

**Comment by frank-zimmermann** [comment]
When moving the search bar into the header, we need to discuss how the search bar should react when the browser window width is smaller.
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/3e0aad25-01a1-4ae3-aaed-57b4b5f24169)

So you need any behavior? Disabling the search button when the window is too small? Or only show the search icon?

**Comment by frank-zimmermann** [comment]
Here, the width of the search needs to be expand 100%.
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/54747568-f6f6-428a-81c4-92471f26e2a3)


![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/b03696d9-dc2d-4516-9e8b-1bbe3e0974f3)

![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/49056485/d874761a-d838-494a-8007-ef82d4b00cfc)

I'm not that expert in CSS.

**Comment by IanMayo** [comment]
Hello Frank, in `oxygen.css` we already have some logic that is screen-width dependent. We  _may_ be able to re-use that pattern to solve this issue.

Aaah, but first  we need to decide the requirement.  I _think_ that the search box should always be visible  - since it's such a quick way to navigate to almost anywhere in the document set.    When  on a wide screen, I guess it could greedily consume the horizontal whitespace.

>  I'm not that expert in CSS.

That's completely fine. When we've got as far as we can, I'll zip up a copy of `target/oxygen` and get one of my web devs to modify the `oxygen.css` to give us what we need.

**Comment by frank-zimmermann** [comment]
@IanMayo , I suggest that you can now send the target folder to the devs. He/she could then modify the `index.html` and move the search to the correct position. When I know how the structure and CSS changed, then I can modify the transformation.
What do you think?

**Comment by IanMayo** [comment]
Sure, I'm happy to do that. But, I'd also like to start considering the useability of the search in the header, in case I can give some direction to the HTML dev - oh and some feedback from the clients.

Would you be able to produce a draft PR that gives us an early version of search-bar-in-header ?    It may be that we drop the PR, but it will allow us to learn about the feature.

**Comment by IanMayo** [comment]
This is now done.
