### ISSUE TITLE
Specify CSS styles in DITA-OT publish step

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Fi3ldMan#97]
We have CSS styling in our Oxygen export template.

But, it would also be useful to see this styling in our `html5` publishing step.

This appears to be the procedure:
https://www.dita-ot.org/dev/topics/html-customization-css

The output from this task will be the command-line instruction necessary to:
* add `template/f13ldman/oxygen.css` to the html5 export in the `LegacyMan` report
* copy the css file to the `target/html` output
* styles observe the styles in the published content.

Note: this is our current DITA publish command:
![image](https://github.com/DeepBlueCLtd/Fi3ldMan/assets/1108513/702fcdc1-c956-4aa5-8f64-2929fe67c327)

`dita -i target/dita/index.ditamap -f html5 -o target/html`

**Comment by brahnavank** [comment]
`dita  -i FieldMan.ditamap -f html5 -o output_dir -v -Dargs.copycss=yes -Dargs.css=oxygen.css -Dargs.cssroot=/Fi3ldMan/dita/resource/ -Dargs.csspath=css/ `

[https://www.dita-ot.org/dev/parameters/parameters-html5](url)

**Comment by IanMayo** [comment]
Ok, this is the command that worked for me:
>  dita -i target/dita/index.ditamap -f html5 -o target/html -Dargs.copycss=yes -Dargs.css=oxygen.css -Dargs.cssroot=/Users/me/git/LegacyMan/template/F13ldMan

Note that the `cssroot` expects an absolute path.  So, I _think_ we have to modify that path in python - so we can't put it into a properties file (which we're trying in #98).

**Comment by IanMayo** [comment]
Fixed in #98
